#!/bin/bash
#
# This little script collects laser cutting time for parts,
# from Trutops generadet PDF files.
# 
# Don't forget use 'detox' (Corrects file and folder names), before use this tool.
#
#
usage="Usage: manutime <folder name>"
#
case $1 in
 "") echo ""
     echo " Missing the folder name."
     echo " $usage"
     exit 1
     ;;
 "-h") echo ""
       echo " $usage"
       exit 0
       ;;
 "--help") echo ""
           echo " $usage"
           exit 0
           ;;
esac
#
print_line(){
	printf "=%.0s" {1..100}
	printf "\n"
}
print_line
echo""
printf "   Collecting data from '"$1"' folder. - Adatok gyűjtése a "$1" mappából. \n"
echo""
print_line
find $1 -type f -name "*pdf" -exec bash -c 'pdfgrep -H "a" {} | cut -d ":" -f1 | uniq && echo""' \; -exec bash -c 'pdfgrep -i -A1000 "méretek:" {} | grep  -i ".GEO" | grep -v "FÁJL NEVE" | rev | cut -d " " -f1 | rev ' \; -exec bash -c 'pdfgrep "MEGMUNKÁLÁSI ID" {} | rev | cut -d " " -f2 | rev' \; -exec printf "=%.0s" {1..100} \; -exec echo "" \;

